Feature. Xcodegen
TouchInstinct/project-template-ios pull request #13
Opened 2018-03-29 19:55 UTC by igorkislyuk

close #7, #10, #12

2018-03-30 07:36 UTC, petropavel13 requested changes

2018-03-30 07:36 UTC, petropavel13 commented on README.md
> +> Пример: если ПАРАМЕТР_2 называется `Bank`, то папка проекта будет называться `Bank-ios`. Уже внутри папки проекта уже будут находится файлы `*.xcodeproj`, `*.xcodeworkspace`, `Podfile`, `Rambafile`
1] Сделай пожалуйста [вот так](https://github.com/TouchInstinct/Styleguide/blob/master/Backend/guides/api_scheme_specification_guide.md#Пример):  утилита [tree](https://en.wikipedia.org/wiki/Tree_(Unix)) тебе в помощь
2] Добавь пример команды с параметрами

2018-03-30 07:36 UTC, petropavel13 commented on README.md
> +- ПАРАМЕТР_3 = Название репозитория с общими строками, без указания расширения гит и названия компании. Пример: `Bank-Common`, `Bank2-Common`
гит -> git

2018-03-30 07:36 UTC, petropavel13 commented on README.md
> +- ПАРАМЕТР_1 = Родительская папка для расположения проекта, в ней будет создана папка проекта.
тильду умеет? `~/Projects/` ?

2018-03-30 07:36 UTC, petropavel13 commented on README.md
> +### Шаг 4. После установки:
Ты не рассказал как mustache поставить:
<img width="602" alt="screen shot 2018-03-30 at 10 34 17" src="https://user-images.githubusercontent.com/6436245/38129048-fe418d50-3405-11e8-8fcf-951968066652.png">

2018-03-30 07:41 UTC, petropavel13 commented on README.md
> +### Шаг 4. После установки:
Двигаемся дальше
<img width="602" alt="screen shot 2018-03-30 at 10 41 05" src="https://user-images.githubusercontent.com/6436245/38129243-e8bfdbd4-3406-11e8-8e2d-5a8e74d7a29c.png">

2018-03-31 08:24 UTC, petropavel13 commented on README.md
> +### Шаг 4. После установки:
Оказывается нужен mustache из гемов. Однако, результат всё ещё остаётся не достижимым.
<img width="602" alt="screen shot 2018-03-31 at 11 22 02" src="https://user-images.githubusercontent.com/6436245/38161343-04abddc8-34d6-11e8-99cd-dd90cc2747f2.png">

2018-04-01 12:06 UTC, arctic-pie commented on README.md
> +> Пример: если ПАРАМЕТР_2 называется `Bank`, то папка проекта будет называться `Bank-ios`. Уже внутри папки проекта уже будут находится файлы `*.xcodeproj`, `*.xcodeworkspace`, `Podfile`, `Rambafile`
Done. Check @petropavel13

2018-04-01 12:07 UTC, arctic-pie commented on README.md
> +- ПАРАМЕТР_3 = Название репозитория с общими строками, без указания расширения гит и названия компании. Пример: `Bank-Common`, `Bank2-Common`
Fixed

2018-04-01 12:07 UTC, arctic-pie commented on README.md
> +### Шаг 4. После установки:
Solved with `Gemfile`, `Brewfile`

2018-04-02 06:37 UTC, petropavel13 requested changes

2018-04-02 06:37 UTC, petropavel13 commented on README.md
> +igorkislyuk$ ./bootstrap.sh ~/Documents/projects/ Bank BankSpbJur-common
Почти хорошо:
```sh
➜  project-template-ios git:(feature/xcodegen) ✗ ./bootstrap.sh ~/Projects Bank Bank-Common       
Clean up folders and files except .git folder...
Initialized empty Git repository in /Users/ivansmolin/Projects/Bank-ios/.git/
Create sources folders...
Creating Analytics ...
Creating Cells ...
Creating Controllers ...
Creating Extensions ...
Creating Generated ...
Creating Models ...
Creating Networking ...
Creating Protocols ...
Creating Resources/Localization ...
Creating Realm ...
Creating Services ...
Creating Views ...
./bootstrap.sh: line 57: bundle: command not found
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 64 (delta 5), reused 20 (delta 2), pack-reused 0
Unpacking objects: 100% (64/64), done.
Tapped 0 formulae (140 files, 189.8KB)
Using yonaskolb/xcodegen
Using xcodegen
Homebrew Bundle complete! 2 Brewfile dependencies now installed.
Generate xcodeproj file...
📋  Loaded spec:
  Name: Bank
  Targets:
    📱  Bank: application
⚙️  Generating project...
⚙️  Writing project...
💾  Saved project to /Users/ivansmolin/Projects/Bank-ios/Bank.xcodeproj
Analyzing dependencies
Downloading dependencies
Installing Crashlytics (3.10.1)
Installing Fabric (1.7.6)
Installing SwiftLint (0.25.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Bank.xcworkspace` for this project from now on.
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem generamba (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/bin/generamba:22:in `<main>'
Cloning into '/Users/ivansmolin/Projects/Bank-ios/common'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:TouchInstinct/Bank-Common.git' into submodule path '/Users/ivansmolin/Projects/Bank-ios/common' failed
Cloning into '/Users/ivansmolin/Projects/Bank-ios/build-scripts'...
remote: Counting objects: 560, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 560 (delta 5), reused 8 (delta 1), pack-reused 539
Receiving objects: 100% (560/560), 145.38 KiB | 600.00 KiB/s, done.
Resolving deltas: 100% (255/255), done.
[master (root-commit) 2abd3c3] Setup project configuration
 28 files changed, 986 insertions(+)
 create mode 100755 .gitattributes
 create mode 100755 .gitignore
 create mode 100644 .gitmodules
 create mode 100644 Bank.xcodeproj/project.pbxproj
 create mode 100644 Bank.xcodeproj/project.xcworkspace/contents.xcworkspacedata
 create mode 100644 Bank.xcworkspace/contents.xcworkspacedata
 create mode 100644 Bank/Analytics/.gitkeep
 create mode 100755 Bank/AppDelegate.swift
 create mode 100644 Bank/Cells/.gitkeep
 create mode 100644 Bank/Controllers/.gitkeep
 create mode 100644 Bank/Extensions/.gitkeep
 create mode 100644 Bank/Generated/.gitkeep
 create mode 100644 Bank/Info.plist
 create mode 100644 Bank/Models/.gitkeep
 create mode 100644 Bank/Networking/.gitkeep
 create mode 100644 Bank/Protocols/.gitkeep
 create mode 100644 Bank/Realm/.gitkeep
 create mode 100755 Bank/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
 create mode 100644 Bank/Resources/LaunchScreen.storyboard
 create mode 100644 Bank/Resources/Localization/.gitkeep
 create mode 100644 Bank/Services/.gitkeep
 create mode 100644 Bank/Views/.gitkeep
 create mode 100644 Podfile
 create mode 100644 Podfile.lock
 create mode 100644 README.md
 create mode 100644 Rambafile
 create mode 160000 build-scripts
 create mode 100644 fastlane/Fastfile
```

2018-04-02 06:37 UTC, petropavel13 commented on README.md
> +igorkislyuk$ ./bootstrap.sh ~/Documents/projects/ Bank BankSpbJur-common
```sh
➜  project-template-ios git:(feature/xcodegen) ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
```

2018-04-02 06:37 UTC, petropavel13 commented on README.md
> +│   ├── Services
Добавь сюда {ProjectName}NumberFormattingService и {ProjectName}DateFormattingService, Первый уже в мастере LeadKit, второй ещё в ревью

2018-04-02 06:37 UTC, petropavel13 commented on sources/project/AppDelegate.swift
>      var window: UIWindow?
Предлагаю window сделать как на Farmy:

```swift
    var window: UIWindow?

    lazy var appWindow: UIWindow = {
        let window = UIWindow(frame: UIScreen.main.bounds)

        self.window = window

        return window
    }()
```

и NavigationService добавь пожалуйста.

можно сразу вот так:

```swift
struct NavigationService {

    private static var appWindow: UIWindow {
        return AppDelegate.shared.appWindow
    }
```

2018-04-02 06:37 UTC, petropavel13 commented on sources/project/AppDelegate.swift
>      var window: UIWindow?
Ну и AppDelegate.shared сразу 

```swift
extension AppDelegate {

    static var shared: AppDelegate {
        let delegate = UIApplication.shared.delegate

        guard let appDelegate = delegate as? AppDelegate else {
            fatalError("Cannot cast \(type(of: delegate)) to AppDelegate")
        }

        return appDelegate
    }

}
```

2018-04-02 06:37 UTC, petropavel13 commented on templates/project.mustache
> +  createIntermediateGroups: true
я бы ещё добавил usesTabs: false и indentWidth: 4 на всякий случай

2018-04-02 06:37 UTC, petropavel13 commented on templates/project.mustache
> +      - path: {{project_name}}/Analytics
Предлагаю добавить папку Appearance со шрифтами, цветами и прочими константами в коде

2018-04-02 06:37 UTC, petropavel13 commented on bootstrap.sh
> +rm  Brewfile*
extra space:)

2018-04-02 06:37 UTC, petropavel13 commented on bootstrap.sh
> +open -a Xcode $PROJECT_NAME.xcworkspace
Можно перед этим ещё генератор запустить руками. Если мы уже условились по какому пути хранится схема. Ну это уже опционально совсем.

2018-04-02 14:14 UTC, igorkislyuk commented on README.md
> +igorkislyuk$ ./bootstrap.sh ~/Documents/projects/ Bank BankSpbJur-common
@petropavel13 It's not default ruby.

2018-04-02 14:15 UTC, igorkislyuk commented on templates/project.mustache
> +      - path: {{project_name}}/Analytics
Пока это делается как отдельные extensions

2018-04-02 14:16 UTC, igorkislyuk commented on bootstrap.sh
> +open -a Xcode $PROJECT_NAME.xcworkspace
В случае с пустой схемой большого профита не будет

2018-04-02 14:16 UTC, igorkislyuk commented on bootstrap.sh
> +rm  Brewfile*
Fixed

2018-04-02 14:19 UTC, igorkislyuk commented on templates/project.mustache
> +  createIntermediateGroups: true
Done

2018-04-02 14:25 UTC, igorkislyuk commented on sources/project/AppDelegate.swift
>      var window: UIWindow?
Ok

2018-04-02 14:25 UTC, igorkislyuk commented on README.md
> +│   ├── Services
Extra generation

2018-04-02 14:26 UTC, igorkislyuk commented on README.md
> +igorkislyuk$ ./bootstrap.sh ~/Documents/projects/ Bank BankSpbJur-common
@petropavel13 make ruby 2.4.0 your default

2018-04-02 16:16 UTC, petropavel13 approved these changes

2018-04-02 16:16 UTC, petropavel13 commented on README.md
> +93 directories, 138 files
зачем оно тут?)

2018-04-02 16:16 UTC, petropavel13 commented on project-example.yml
> +      - script: . build-scripts/xcode/build_phases/api_generator.sh 1.1.5
1.1.8

2018-04-02 16:16 UTC, petropavel13 commented on project-example.yml
> +  xcodeVersion: 9.2
9.3?

2018-04-02 16:16 UTC, petropavel13 commented on project-example.yml
> +name: TestProject
А зачем нам этот файл?

2018-04-02 16:16 UTC, petropavel13 commented on templates/project.mustache
> +  xcodeVersion: 9.2
9.3?

2018-04-02 16:16 UTC, petropavel13 commented on templates/project.mustache
> +      - script: ". build-scripts/xcode/build_phases/api_generator.sh 1.1.5"
1.1.8

2018-04-02 16:26 UTC, igorkislyuk commented on project-example.yml
> +name: TestProject
Верно!

2018-04-02 17:03 UTC, scoreyou approved these changes

2018-04-02 17:04 UTC, merged